name: create-rule-meta.json
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout self repository
        uses: actions/checkout@v4

      - name: Checkout hayabusa-rules
        uses: actions/checkout@v4
        with:
          repository: Yamato-Security/hayabusa-rules
          path: hayabusa-rules

      - name: Run
        run: cargo run --release -- ./hayabusa-rules ./eid_subcategory_mapping.csv ./wela_security_rules.json
